version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TokyoJoe138!
    volumes:
      - mongo-data:/data/db


  mongo-express:
    image: mongo-express:latest
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=TokyoJoe138!
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: always
    
    
volumes:
  mongo-data:

  